// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CreateProfileEndpointApiProfilesPostData, CreateProfileEndpointApiProfilesPostErrors, CreateProfileEndpointApiProfilesPostResponses, DeleteProfileEndpointApiProfilesProfileIdDeleteData, DeleteProfileEndpointApiProfilesProfileIdDeleteErrors, DeleteProfileEndpointApiProfilesProfileIdDeleteResponses, GenerateLabelPdfLabelsPdfPostData, GenerateLabelPdfLabelsPdfPostErrors, GenerateLabelPdfLabelsPdfPostResponses, GetConfigApiConfigGetData, GetConfigApiConfigGetResponses, GetStateApiStateGetData, GetStateApiStateGetResponses, PrintLabelPrintPostData, PrintLabelPrintPostErrors, PrintLabelPrintPostResponses, SaveConfigApiConfigPostData, SaveConfigApiConfigPostErrors, SaveConfigApiConfigPostResponses, SelectProfileEndpointApiProfilesProfileIdSelectPostData, SelectProfileEndpointApiProfilesProfileIdSelectPostErrors, SelectProfileEndpointApiProfilesProfileIdSelectPostResponses, UpdateProfileEndpointApiProfilesProfileIdPutData, UpdateProfileEndpointApiProfilesProfileIdPutErrors, UpdateProfileEndpointApiProfilesProfileIdPutResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get Config
 */
export const getConfigApiConfigGet = <ThrowOnError extends boolean = false>(options?: Options<GetConfigApiConfigGetData, ThrowOnError>) => (options?.client ?? client).get<GetConfigApiConfigGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/config',
    ...options
});

/**
 * Save Config
 */
export const saveConfigApiConfigPost = <ThrowOnError extends boolean = false>(options: Options<SaveConfigApiConfigPostData, ThrowOnError>) => (options.client ?? client).post<SaveConfigApiConfigPostResponses, SaveConfigApiConfigPostErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/config',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Create Profile Endpoint
 */
export const createProfileEndpointApiProfilesPost = <ThrowOnError extends boolean = false>(options: Options<CreateProfileEndpointApiProfilesPostData, ThrowOnError>) => (options.client ?? client).post<CreateProfileEndpointApiProfilesPostResponses, CreateProfileEndpointApiProfilesPostErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/profiles',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Delete Profile Endpoint
 */
export const deleteProfileEndpointApiProfilesProfileIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteProfileEndpointApiProfilesProfileIdDeleteData, ThrowOnError>) => (options.client ?? client).delete<DeleteProfileEndpointApiProfilesProfileIdDeleteResponses, DeleteProfileEndpointApiProfilesProfileIdDeleteErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/profiles/{profile_id}',
    ...options
});

/**
 * Update Profile Endpoint
 */
export const updateProfileEndpointApiProfilesProfileIdPut = <ThrowOnError extends boolean = false>(options: Options<UpdateProfileEndpointApiProfilesProfileIdPutData, ThrowOnError>) => (options.client ?? client).put<UpdateProfileEndpointApiProfilesProfileIdPutResponses, UpdateProfileEndpointApiProfilesProfileIdPutErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/profiles/{profile_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Select Profile Endpoint
 */
export const selectProfileEndpointApiProfilesProfileIdSelectPost = <ThrowOnError extends boolean = false>(options: Options<SelectProfileEndpointApiProfilesProfileIdSelectPostData, ThrowOnError>) => (options.client ?? client).post<SelectProfileEndpointApiProfilesProfileIdSelectPostResponses, SelectProfileEndpointApiProfilesProfileIdSelectPostErrors, ThrowOnError>({
    responseType: 'json',
    url: '/api/profiles/{profile_id}/select',
    ...options
});

/**
 * Get State
 */
export const getStateApiStateGet = <ThrowOnError extends boolean = false>(options?: Options<GetStateApiStateGetData, ThrowOnError>) => (options?.client ?? client).get<GetStateApiStateGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/api/state',
    ...options
});

/**
 * Generate Label Pdf
 */
export const generateLabelPdfLabelsPdfPost = <ThrowOnError extends boolean = false>(options: Options<GenerateLabelPdfLabelsPdfPostData, ThrowOnError>) => (options.client ?? client).post<GenerateLabelPdfLabelsPdfPostResponses, GenerateLabelPdfLabelsPdfPostErrors, ThrowOnError>({
    responseType: 'blob',
    url: '/labels.pdf',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Print Label
 */
export const printLabelPrintPost = <ThrowOnError extends boolean = false>(options: Options<PrintLabelPrintPostData, ThrowOnError>) => (options.client ?? client).post<PrintLabelPrintPostResponses, PrintLabelPrintPostErrors, ThrowOnError>({
    responseType: 'json',
    url: '/print',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});
