// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * AppState
 */
export type AppState = {
    /**
     * Profiles
     */
    profiles?: Array<LabelProfile>;
    /**
     * Queue Name
     */
    queue_name: string;
    /**
     * Selected Profile Id
     */
    selected_profile_id?: string | null;
    /**
     * Stock Is Continuous
     */
    stock_is_continuous?: boolean;
    /**
     * Stock Length Mm
     */
    stock_length_mm?: number | null;
    /**
     * Stock Width Mm
     */
    stock_width_mm?: number;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LabelBorderInput
 */
export type LabelBorderInput = {
    /**
     * Enabled
     */
    enabled?: boolean;
    /**
     * Inset Mm
     */
    inset_mm?: number;
    /**
     * Radius Mm
     */
    radius_mm?: number;
    /**
     * Thickness Mm
     */
    thickness_mm?: number;
};

/**
 * LabelProfile
 */
export type LabelProfile = {
    border?: LabelBorderInput;
    /**
     * Cut Every
     */
    cut_every?: number;
    /**
     * Height Mm
     */
    height_mm: number;
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Quality
     */
    quality?: string;
    /**
     * Quantity
     */
    quantity?: number;
    /**
     * Rows
     */
    rows: Array<LabelRowInput>;
    /**
     * Width Mm
     */
    width_mm: number;
};

/**
 * LabelProfileInput
 */
export type LabelProfileInput = {
    border?: LabelBorderInput;
    /**
     * Cut Every
     */
    cut_every?: number;
    /**
     * Height Mm
     */
    height_mm: number;
    /**
     * Name
     */
    name: string;
    /**
     * Quality
     */
    quality?: string;
    /**
     * Quantity
     */
    quantity?: number;
    /**
     * Rows
     */
    rows: Array<LabelRowInput>;
    /**
     * Width Mm
     */
    width_mm: number;
};

/**
 * LabelRowInput
 */
export type LabelRowInput = {
    /**
     * Alignment
     */
    alignment?: string;
    /**
     * Bold
     */
    bold?: boolean;
    /**
     * Italic
     */
    italic?: boolean;
    /**
     * Level
     */
    level?: string;
    /**
     * Text
     */
    text?: string;
};

/**
 * PrintJobResult
 */
export type PrintJobResult = {
    /**
     * Ok
     */
    ok: boolean;
    /**
     * Queue
     */
    queue: string;
    /**
     * Stderr
     */
    stderr?: string;
    /**
     * Stdout
     */
    stdout?: string;
};

/**
 * QueueConfig
 */
export type QueueConfig = {
    /**
     * Queue Name
     */
    queue_name: string;
    /**
     * Stock Is Continuous
     */
    stock_is_continuous?: boolean;
    /**
     * Stock Length Mm
     */
    stock_length_mm?: number | null;
    /**
     * Stock Width Mm
     */
    stock_width_mm?: number;
};

/**
 * QueueState
 */
export type QueueState = {
    /**
     * Default Queue
     */
    default_queue?: string | null;
    /**
     * Queue Name
     */
    queue_name: string;
    /**
     * Queues
     */
    queues?: Array<string>;
    /**
     * Stock Is Continuous
     */
    stock_is_continuous?: boolean;
    /**
     * Stock Length Mm
     */
    stock_length_mm?: number | null;
    /**
     * Stock Width Mm
     */
    stock_width_mm?: number;
};

/**
 * QueueStatus
 */
export type QueueStatus = {
    /**
     * Detail
     */
    detail?: string | null;
    /**
     * Is Detected
     */
    is_detected?: boolean;
    /**
     * Is Online
     */
    is_online?: boolean;
    /**
     * Job Ids
     */
    job_ids?: Array<string>;
    /**
     * Queue Name
     */
    queue_name: string;
    /**
     * Queued Jobs
     */
    queued_jobs?: number;
    /**
     * Status
     */
    status?: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type GetConfigApiConfigGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/config';
};

export type GetConfigApiConfigGetResponses = {
    /**
     * Successful Response
     */
    200: QueueState;
};

export type GetConfigApiConfigGetResponse = GetConfigApiConfigGetResponses[keyof GetConfigApiConfigGetResponses];

export type SaveConfigApiConfigPostData = {
    body: QueueConfig;
    path?: never;
    query?: never;
    url: '/api/config';
};

export type SaveConfigApiConfigPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SaveConfigApiConfigPostError = SaveConfigApiConfigPostErrors[keyof SaveConfigApiConfigPostErrors];

export type SaveConfigApiConfigPostResponses = {
    /**
     * Successful Response
     */
    200: QueueState;
};

export type SaveConfigApiConfigPostResponse = SaveConfigApiConfigPostResponses[keyof SaveConfigApiConfigPostResponses];

export type GetConfigOptionsApiConfigOptionsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Queue Name
         */
        queue_name?: string | null;
    };
    url: '/api/config/options';
};

export type GetConfigOptionsApiConfigOptionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetConfigOptionsApiConfigOptionsGetError = GetConfigOptionsApiConfigOptionsGetErrors[keyof GetConfigOptionsApiConfigOptionsGetErrors];

export type GetConfigOptionsApiConfigOptionsGetResponses = {
    /**
     * Response Get Config Options Api Config Options Get
     *
     * Successful Response
     */
    200: {
        [key: string]: {
            [key: string]: string | Array<string> | null;
        };
    };
};

export type GetConfigOptionsApiConfigOptionsGetResponse = GetConfigOptionsApiConfigOptionsGetResponses[keyof GetConfigOptionsApiConfigOptionsGetResponses];

export type CreateProfileEndpointApiProfilesPostData = {
    body: LabelProfileInput;
    path?: never;
    query?: never;
    url: '/api/profiles';
};

export type CreateProfileEndpointApiProfilesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateProfileEndpointApiProfilesPostError = CreateProfileEndpointApiProfilesPostErrors[keyof CreateProfileEndpointApiProfilesPostErrors];

export type CreateProfileEndpointApiProfilesPostResponses = {
    /**
     * Successful Response
     */
    200: AppState;
};

export type CreateProfileEndpointApiProfilesPostResponse = CreateProfileEndpointApiProfilesPostResponses[keyof CreateProfileEndpointApiProfilesPostResponses];

export type DeleteProfileEndpointApiProfilesProfileIdDeleteData = {
    body?: never;
    path: {
        /**
         * Profile Id
         */
        profile_id: string;
    };
    query?: never;
    url: '/api/profiles/{profile_id}';
};

export type DeleteProfileEndpointApiProfilesProfileIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteProfileEndpointApiProfilesProfileIdDeleteError = DeleteProfileEndpointApiProfilesProfileIdDeleteErrors[keyof DeleteProfileEndpointApiProfilesProfileIdDeleteErrors];

export type DeleteProfileEndpointApiProfilesProfileIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: AppState;
};

export type DeleteProfileEndpointApiProfilesProfileIdDeleteResponse = DeleteProfileEndpointApiProfilesProfileIdDeleteResponses[keyof DeleteProfileEndpointApiProfilesProfileIdDeleteResponses];

export type UpdateProfileEndpointApiProfilesProfileIdPutData = {
    body: LabelProfileInput;
    path: {
        /**
         * Profile Id
         */
        profile_id: string;
    };
    query?: never;
    url: '/api/profiles/{profile_id}';
};

export type UpdateProfileEndpointApiProfilesProfileIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateProfileEndpointApiProfilesProfileIdPutError = UpdateProfileEndpointApiProfilesProfileIdPutErrors[keyof UpdateProfileEndpointApiProfilesProfileIdPutErrors];

export type UpdateProfileEndpointApiProfilesProfileIdPutResponses = {
    /**
     * Successful Response
     */
    200: AppState;
};

export type UpdateProfileEndpointApiProfilesProfileIdPutResponse = UpdateProfileEndpointApiProfilesProfileIdPutResponses[keyof UpdateProfileEndpointApiProfilesProfileIdPutResponses];

export type SelectProfileEndpointApiProfilesProfileIdSelectPostData = {
    body?: never;
    path: {
        /**
         * Profile Id
         */
        profile_id: string;
    };
    query?: never;
    url: '/api/profiles/{profile_id}/select';
};

export type SelectProfileEndpointApiProfilesProfileIdSelectPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SelectProfileEndpointApiProfilesProfileIdSelectPostError = SelectProfileEndpointApiProfilesProfileIdSelectPostErrors[keyof SelectProfileEndpointApiProfilesProfileIdSelectPostErrors];

export type SelectProfileEndpointApiProfilesProfileIdSelectPostResponses = {
    /**
     * Successful Response
     */
    200: AppState;
};

export type SelectProfileEndpointApiProfilesProfileIdSelectPostResponse = SelectProfileEndpointApiProfilesProfileIdSelectPostResponses[keyof SelectProfileEndpointApiProfilesProfileIdSelectPostResponses];

export type GetQueueStatusApiQueueStatusGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Queue Name
         */
        queue_name?: string | null;
    };
    url: '/api/queue-status';
};

export type GetQueueStatusApiQueueStatusGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetQueueStatusApiQueueStatusGetError = GetQueueStatusApiQueueStatusGetErrors[keyof GetQueueStatusApiQueueStatusGetErrors];

export type GetQueueStatusApiQueueStatusGetResponses = {
    /**
     * Successful Response
     */
    200: QueueStatus;
};

export type GetQueueStatusApiQueueStatusGetResponse = GetQueueStatusApiQueueStatusGetResponses[keyof GetQueueStatusApiQueueStatusGetResponses];

export type GetStateApiStateGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/state';
};

export type GetStateApiStateGetResponses = {
    /**
     * Successful Response
     */
    200: AppState;
};

export type GetStateApiStateGetResponse = GetStateApiStateGetResponses[keyof GetStateApiStateGetResponses];

export type GenerateLabelPdfLabelsPdfPostData = {
    body: LabelProfileInput;
    path?: never;
    query?: never;
    url: '/labels.pdf';
};

export type GenerateLabelPdfLabelsPdfPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GenerateLabelPdfLabelsPdfPostError = GenerateLabelPdfLabelsPdfPostErrors[keyof GenerateLabelPdfLabelsPdfPostErrors];

export type GenerateLabelPdfLabelsPdfPostResponses = {
    /**
     * Successful Response
     */
    200: Blob | File;
};

export type GenerateLabelPdfLabelsPdfPostResponse = GenerateLabelPdfLabelsPdfPostResponses[keyof GenerateLabelPdfLabelsPdfPostResponses];

export type PrintLabelPrintPostData = {
    body: LabelProfileInput;
    path?: never;
    query?: never;
    url: '/print';
};

export type PrintLabelPrintPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PrintLabelPrintPostError = PrintLabelPrintPostErrors[keyof PrintLabelPrintPostErrors];

export type PrintLabelPrintPostResponses = {
    /**
     * Successful Response
     */
    200: PrintJobResult;
};

export type PrintLabelPrintPostResponse = PrintLabelPrintPostResponses[keyof PrintLabelPrintPostResponses];
